version: '3.8'

services:
  app:
    depends_on:
      - mysqldb
    build:
      context: .
    ports:
      - 8081:8080 # port on host, port on container 绑定容器端口到主机端口
    env_file:
      - ./.env
    environment:
        - DB_HOST=$MYSQLDB_HOST
        - DB_USER=$MYSQLDB_USER
        - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - DB_NAME=$MYSQLDB_DATABASE
        - PORT=$APP_PORT
        - HOST=$APP_HOST
    networks:
        api_server_default:
            ipv4_address: 172.23.0.3

  mysqldb:
    image: mysql:5.7.38
    ports:
      - 3309:3307 # 此处的端口mapping对于app和mysql的连接无意义，因为app容器与mysqldb容器是通过network通讯，而不是通过端口映射
    env_file:
      - ./.env
    environment:
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
        api_server_default:
            ipv4_address: 172.23.0.2

volumes:
  db:

networks:
  api_server_default:
    ipam:
        config:
            - subnet: 172.23.0.0/16